title: Eunji Byun
baseURL: https://ebyun.netlify.app
theme: hugo-researcher
disableKinds:
  - taxonomy
  - term
enableEmoji: yes
math: no
googleAnalytics: ''
params:
  author: Eunji Byun
  description: A simple monospaced resume theme for Hugo.
  favicon: favicon.ico
  footer:
    text: Powered by Hugo Researcher
    url: https://github.com/ojroques/hugo-researcher
  logo: ''
  socialIcons:
    - icon: fab fa-github
      title: Github
      url: https://github.com/ojroques/hugo-researcher
  style:
    avatarSize: 90px
    colorBlack: '#222222'
    colorRed: '#dc3545'
    fontFamily: Inconsolata
    pageWidth: 750px
permalinks:
  /: /:filename
menu:
  main:
    - name: About
      url: /about
      weight: 1
    - name: Research
      url: /research
      weight: 2
    - name: Contact
      url: /contact
      weight: 3
markup:
  goldmark:
    renderer:
      unsafe: yes
